use std::{env, fs, path::PathBuf};

/// Default RAM counters buffer size in 32-bit words.
const DEFAULT_RAM_SIZE_WORDS: usize = 64;
/// Default size of both buffers in 32-bit words on a host. Memory is cheap there, and tests running in parallel
/// threads each need their own `Counters` statics, which add up.
const DEFAULT_HOST_SIZE_WORDS: usize = 100 * DEFAULT_RAM_SIZE_WORDS;
/// Memory region in which the BKP counters buffer is placed, unless overridden by `CNT_BKP_MEMORY_REGION`.
const DEFAULT_BKP_REGION: &str = "BKPSRAM";

fn main() {
    println!("cargo:rerun-if-env-changed=CNT_RAM_BUFFER_SIZE_WORDS");
    println!("cargo:rerun-if-env-changed=CNT_BKP_BUFFER_SIZE_WORDS");
    println!("cargo:rerun-if-env-changed=CNT_BKP_MEMORY_REGION");
    println!("cargo:rerun-if-changed=build.rs");

    let host = env::var("CARGO_CFG_TARGET_OS").is_ok_and(|os| os != "none");
    let ram_size = size_words(
        "CNT_RAM_BUFFER_SIZE_WORDS",
        if host {
            DEFAULT_HOST_SIZE_WORDS
        } else {
            DEFAULT_RAM_SIZE_WORDS
        },
    );
    // There is no BKP memory region to place the buffer in on a host, so it is an ordinary static there and need not
    // be opted into
    let bkp_size = size_words(
        "CNT_BKP_BUFFER_SIZE_WORDS",
        if host { DEFAULT_HOST_SIZE_WORDS } else { 0 },
    );
    let bkp_region =
        env::var("CNT_BKP_MEMORY_REGION").unwrap_or_else(|_| DEFAULT_BKP_REGION.to_string());

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());

    fs::write(
        out_dir.join("consts.rs"),
        format!(
            "/// RAM counters buffer size in 32-bit words (default: {DEFAULT_RAM_SIZE_WORDS}, {DEFAULT_HOST_SIZE_WORDS} on a host).
            ///
            /// Can be customized by setting the `CNT_RAM_BUFFER_SIZE_WORDS` environment variable.
            pub(crate) const RAM_BUF_SIZE: usize = {ram_size};

            /// BKP counters buffer size in 32-bit words (default: 0, {DEFAULT_HOST_SIZE_WORDS} on a host).
            ///
            /// Can be customized by setting the `CNT_BKP_BUFFER_SIZE_WORDS` environment variable.
            pub(crate) const BKP_BUF_SIZE: usize = {bkp_size};"
        ),
    )
    .unwrap();

    // Put the linker script where the linker can find it. With the `disabled` feature nothing is emitted by the
    // macros, an empty script keeps an existing `-Tcnt.x` link argument working.
    let script = if env::var_os("CARGO_FEATURE_DISABLED").is_some() {
        "/* Generated by the cnt crate's build script, counters are disabled */\n".to_string()
    } else {
        linker_script(ram_size, bkp_size, &bkp_region)
    };
    fs::write(out_dir.join("cnt.x"), script).unwrap();
    println!("cargo:rustc-link-search={}", out_dir.display());
}

fn size_words(var: &str, default: usize) -> usize {
    match env::var(var) {
        Ok(s) => s
            .trim()
            .parse()
            .unwrap_or_else(|e| panic!("could not parse {var}={s:?} as usize: {e}")),
        Err(_) => default,
    }
}

/// The `cnt.x` linker script.
///
/// Counter indices are the addresses of one-byte-per-word marker statics, placed in non-allocated (INFO) sections
/// starting at address 0. `__*_COUNTERS_MARKER_END` is therefore the number of words in use, which lets the linker
/// reject firmware whose counters would not fit into the buffer.
///
/// `.cnt_layout` holds one marker per `#[derive(Count)]` type, its address identifies the layout. `.cnt_instance`
/// holds one `InstanceInfo` per `counters!` invocation, with pointers to its slots marker and layout marker, which the
/// linker resolves in the ELF for host tools.
fn linker_script(ram_size: usize, bkp_size: usize, bkp_region: &str) -> String {
    let mut script = String::from(
        "/* Generated by the cnt crate's build script, see build.rs */
SECTIONS
{
  .counters_ram 0 (INFO) :
  {
    *(.cnt_ram.*);
    __RAM_COUNTERS_MARKER_END = .;
  }

  .counters_bkp 0 (INFO) :
  {
    *(.cnt_bkp.*);
    __BKP_COUNTERS_MARKER_END = .;
  }

  .cnt_layout 0 (INFO) :
  {
    *(.cnt_layout.*);
  }

  .cnt_instance 0 (INFO) :
  {
    *(.cnt_instance.*);
  }
",
    );
    if bkp_size > 0 {
        // Only when BKP counters are in use, so that a memory region is not required otherwise. The buffer must not be
        // initialized by the startup code (NOLOAD, outside of .bss/.data), or it would not survive a reset.
        script.push_str(&format!(
            "
  .cnt_bkp_buffer (NOLOAD) :
  {{
    . = ALIGN(4);
    KEEP(*(.cnt_bkp_buffer .cnt_bkp_buffer.*));
  }} > {bkp_region}
"
        ));
    }
    script.push_str(&format!(
        "}}

ASSERT(__RAM_COUNTERS_MARKER_END <= {ram_size},
  \"cnt: too many RAM counters for a buffer of {ram_size} words, increase CNT_RAM_BUFFER_SIZE_WORDS\");
ASSERT(__BKP_COUNTERS_MARKER_END <= {bkp_size},
  \"cnt: too many BKP counters for a buffer of {bkp_size} words, increase CNT_BKP_BUFFER_SIZE_WORDS\");
"
    ));
    script
}
