[package]
name = "cnt_core"
description = "Host data types and ELF parsing for the embedded counters crate - cnt"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
gimli = "0.34.0"
object = "0.39.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"