[workspace]
resolver = "3"
members = ["cnt", "cnt_cli", "cnt_core", "cnt_macro"]

[workspace.package]
version = "0.4.0"
edition = "2024"
rust-version = "1.88"
authors = ["Roman Isaikin <romix.lab@gmail.com>"]
license = "MIT"
description = "When logging is not an option - count"
repository = "https://github.com/romixlab/cnt"

[workspace.dependencies]
anyhow = "1.0"
cnt_core = { path = "./cnt_core", version = "0.4" }
cnt_macro = { path = "./cnt_macro", version = "0.4" }
