[workspace.package]
version = "0.2.0"
edition = "2024"
authors = ["Roman Isaikin <romix.lab@gmail.com>"]
license = "MIT"
description = "When logging is not an option - count"
repository = "https://github.com/romixlab/cnt"

[workspace]
resolver = "3"

members = ["cnt", "cnt_macro", "cnt_core", "cnt_cli"]

[workspace.dependencies]
anyhow = "1.0"
