//! The counter buffers and the increment functions used by the generated code. Not compiled with the `disabled`
//! feature.

use crate::consts::{BKP_BUF_SIZE, RAM_BUF_SIZE};
use core::sync::atomic::{AtomicU32, Ordering};

// The buffers are arrays of atomics rather than `static mut [u32; N]`:
// - no `&mut` or `&` to the buffer is ever created, so an interrupt updating one counter while another is being
//   updated is not UB (with a `static mut` even handing out a `&'static [u32]` from `counters_ram_buffer` would be
//   UB, as the buffer keeps changing behind it).
// - `Relaxed` loads and stores compile to plain `ldr`/`str` on all Cortex-M cores, including thumbv6m, so there is
//   no cost compared to non-atomic accesses.
//
// Every counter has its own word(s) in a buffer. The index of a counter is the address of a marker static, one byte
// per 32-bit word of the counter, placed in a non-allocated (INFO) section starting at 0 (see build.rs), so the linker
// hands out non-repeating indices. Markers are emitted per `cnt!` call site and per `counters!` instance.
//
// On cores with atomic read-modify-write instructions (`target_has_atomic = "32"`, e.g. thumbv7m+) counters are
// updated with `fetch_add`/`fetch_update`, so an update preempted by an interrupt updating the same counter is not
// lost. On cores without them (thumbv6m) a plain load-add-store is used; an update from a call site that runs both in
// thread mode and in an interrupt may then be lost. u64 counters are two words, so they may be read torn while an
// increment is carrying into the high word, from the host or through `counters_ram_buffer`.

#[unsafe(no_mangle)]
static _CNT_RAM_BUFFER: [AtomicU32; RAM_BUF_SIZE] = [const { AtomicU32::new(0) }; RAM_BUF_SIZE];

/// Non-volatile counters. The buffer must be placed into memory that survives a reset and is not initialized by the
/// startup code, `cnt.x` puts it into the `BKPSRAM` memory region (or the one given via `CNT_BKP_MEMORY_REGION`) when
/// `CNT_BKP_BUFFER_SIZE_WORDS` is non-zero.
#[unsafe(no_mangle)]
#[cfg_attr(target_os = "macos", unsafe(link_section = ".bss,cnt_bkp_buffer"))]
#[cfg_attr(not(target_os = "macos"), unsafe(link_section = ".cnt_bkp_buffer"))]
static _CNT_BKP_BUFFER: [AtomicU32; BKP_BUF_SIZE] = [const { AtomicU32::new(0) }; BKP_BUF_SIZE];

/// RAM counters, as 32-bit words. u64 counters occupy two words, low word first.
///
/// Values keep changing while the slice is alive, read them with [`AtomicU32::load`] (`Relaxed` is enough). A u64
/// counter may be torn if read while it is being incremented.
#[inline(always)]
pub fn counters_ram_buffer() -> &'static [AtomicU32] {
    &_CNT_RAM_BUFFER
}

/// BKP counters, as 32-bit words. See [`counters_ram_buffer`].
#[inline(always)]
pub fn counters_bkp_buffer() -> &'static [AtomicU32] {
    &_CNT_BKP_BUFFER
}

/// Add `rhs` to a u32 RAM counter, saturating at the maximum value. Used by the code generated by the cnt macros.
///
/// Panics if `counter_idx` is out of bounds, which can only happen if the `cnt.x` linker script is not used, as it
/// rejects firmware with more counters than the buffer can hold.
#[inline(always)]
pub fn saturating_add_u32_ram(counter_idx: usize, rhs: u32) {
    saturating_add_u32(&_CNT_RAM_BUFFER[counter_idx], rhs);
}

/// Add `rhs` to a u32 BKP counter, saturating at the maximum value. Used by the code generated by the cnt macros.
///
/// Panics if `counter_idx` is out of bounds, see [`saturating_add_u32_ram`].
#[inline(always)]
pub fn saturating_add_u32_bkp(counter_idx: usize, rhs: u32) {
    saturating_add_u32(&_CNT_BKP_BUFFER[counter_idx], rhs);
}

/// Add `rhs` to a u64 RAM counter stored at words `counter_idx_lo` and `counter_idx_lo + 1`, saturating at the maximum
/// value. Used by the code generated by the cnt macros.
///
/// Panics if the counter is out of bounds, see [`saturating_add_u32_ram`].
#[inline(always)]
pub fn saturating_add_u64_ram(counter_idx_lo: usize, rhs: u64) {
    saturating_add_u64(&_CNT_RAM_BUFFER[counter_idx_lo..counter_idx_lo + 2], rhs);
}

/// Add `rhs` to a u64 BKP counter stored at words `counter_idx_lo` and `counter_idx_lo + 1`, saturating at the maximum
/// value. Used by the code generated by the cnt macros.
///
/// Panics if the counter is out of bounds, see [`saturating_add_u32_ram`].
#[inline(always)]
pub fn saturating_add_u64_bkp(counter_idx_lo: usize, rhs: u64) {
    saturating_add_u64(&_CNT_BKP_BUFFER[counter_idx_lo..counter_idx_lo + 2], rhs);
}

#[inline(always)]
fn saturating_add_u32(counter: &AtomicU32, rhs: u32) {
    #[cfg(target_has_atomic = "32")]
    saturating_add_u32_atomic(counter, rhs);
    #[cfg(not(target_has_atomic = "32"))]
    saturating_add_u32_plain(counter, rhs);
}

/// Add `rhs` to the u64 stored in `words` as two 32-bit words, low word first.
///
/// The buffers are only 4-byte aligned, so a u64 counter is accessed as two u32 words instead of through an
/// (unaligned) `u64`. This also avoids byte-wise unaligned accesses on cores without unaligned access support.
#[inline(always)]
fn saturating_add_u64(words: &[AtomicU32], rhs: u64) {
    let [lo, hi] = words else { unreachable!() };
    #[cfg(target_has_atomic = "32")]
    saturating_add_u64_atomic(lo, hi, rhs);
    #[cfg(not(target_has_atomic = "32"))]
    saturating_add_u64_plain(lo, hi, rhs);
}

/// Read-modify-write loop (`ldrex`/`strex` on Cortex-M), an update preempted by another update of the same counter
/// is retried instead of lost.
#[cfg(any(target_has_atomic = "32", test))]
#[inline(always)]
fn saturating_add_u32_atomic(counter: &AtomicU32, rhs: u32) {
    // The closure never returns None, so this cannot fail
    let _ = counter.fetch_update(Ordering::Relaxed, Ordering::Relaxed, |v| {
        Some(v.saturating_add(rhs))
    });
}

/// Plain load, add, store for cores without atomic read-modify-write instructions (thumbv6m).
#[cfg(any(not(target_has_atomic = "32"), test))]
#[inline(always)]
fn saturating_add_u32_plain(counter: &AtomicU32, rhs: u32) {
    counter.store(
        counter.load(Ordering::Relaxed).saturating_add(rhs),
        Ordering::Relaxed,
    );
}

/// Low word is added atomically, a carry is then added to the high word atomically. Neither update can be lost, but a
/// reader may observe the value between the two stores. Saturation is best-effort: once the high word saturates, the
/// low word is set to the maximum as well.
#[cfg(any(target_has_atomic = "32", test))]
#[inline(always)]
fn saturating_add_u64_atomic(lo: &AtomicU32, hi: &AtomicU32, rhs: u64) {
    let rhs_lo = rhs as u32;
    let rhs_hi = (rhs >> 32) as u32;
    let old_lo = lo.fetch_add(rhs_lo, Ordering::Relaxed);
    let (_, carry) = old_lo.overflowing_add(rhs_lo);
    // Overflows only when the sum exceeds u64::MAX anyway, so saturating is correct here
    let inc_hi = rhs_hi.saturating_add(carry as u32);
    if inc_hi == 0 {
        return;
    }
    let Ok(old_hi) = hi.fetch_update(Ordering::Relaxed, Ordering::Relaxed, |h| {
        Some(h.saturating_add(inc_hi))
    }) else {
        unreachable!()
    };
    if old_hi.checked_add(inc_hi).is_none() {
        lo.store(u32::MAX, Ordering::Relaxed);
    }
}

#[cfg(any(not(target_has_atomic = "32"), test))]
#[inline(always)]
fn saturating_add_u64_plain(lo: &AtomicU32, hi: &AtomicU32, rhs: u64) {
    let value = (u64::from(hi.load(Ordering::Relaxed)) << 32
        | u64::from(lo.load(Ordering::Relaxed)))
    .saturating_add(rhs);
    lo.store(value as u32, Ordering::Relaxed);
    hi.store((value >> 32) as u32, Ordering::Relaxed);
}

#[cfg(test)]
mod tests {
    use super::*;

    fn words(lo: &AtomicU32, hi: &AtomicU32) -> [u32; 2] {
        [lo.load(Ordering::Relaxed), hi.load(Ordering::Relaxed)]
    }

    const U64_IMPLS: [fn(&AtomicU32, &AtomicU32, u64); 2] =
        [saturating_add_u64_atomic, saturating_add_u64_plain];
    const U32_IMPLS: [fn(&AtomicU32, u32); 2] =
        [saturating_add_u32_atomic, saturating_add_u32_plain];

    #[test]
    fn u64_carries_into_high_word() {
        for add in U64_IMPLS {
            let (lo, hi) = (AtomicU32::new(u32::MAX), AtomicU32::new(0));
            add(&lo, &hi, 1);
            assert_eq!(words(&lo, &hi), [0, 1]);
            add(&lo, &hi, 0x1_0000_0002);
            assert_eq!(words(&lo, &hi), [2, 2]);
            add(&lo, &hi, 3 << 32);
            assert_eq!(words(&lo, &hi), [2, 5]);
            add(&lo, &hi, u64::from(u32::MAX) << 32);
            assert_eq!(words(&lo, &hi), [u32::MAX, u32::MAX]);
        }
    }

    #[test]
    fn u64_saturates() {
        for add in U64_IMPLS {
            let (lo, hi) = (AtomicU32::new(u32::MAX - 1), AtomicU32::new(u32::MAX));
            add(&lo, &hi, 5);
            assert_eq!(words(&lo, &hi), [u32::MAX, u32::MAX]);
            add(&lo, &hi, 1);
            assert_eq!(words(&lo, &hi), [u32::MAX, u32::MAX]);
        }
    }

    #[test]
    fn u32_saturates() {
        for add in U32_IMPLS {
            let counter = AtomicU32::new(u32::MAX - 1);
            add(&counter, 5);
            assert_eq!(counter.load(Ordering::Relaxed), u32::MAX);
        }
    }

    #[test]
    #[should_panic]
    fn u64_out_of_bounds_panics() {
        saturating_add_u64_ram(RAM_BUF_SIZE - 1, 1);
    }
}
