#![no_std]

use crate::consts::{BKP_BUF_SIZE, RAM_BUF_SIZE};
pub use cnt_macro::{bkp_cnt_if, cnt_if};

mod consts;

#[used]
#[unsafe(no_mangle)]
#[cfg_attr(target_os = "macos", unsafe(link_section = ".rodata,cnt_signature"))]
#[cfg_attr(
    not(target_os = "macos"),
    unsafe(link_section = ".rodata.cnt_signature")
)]
static mut _CNT_SIGNATURE: [u8; 8] = [0; 8];

#[unsafe(no_mangle)]
static mut _CNT_RAM_BUFFER: [u32; RAM_BUF_SIZE] = [0; RAM_BUF_SIZE];

#[inline(always)]
pub fn counters_ram_buffer() -> &'static [u32] {
    unsafe {
        core::slice::from_raw_parts(
            &raw const _CNT_RAM_BUFFER as *const _ as *const u32,
            RAM_BUF_SIZE,
        )
    }
}

#[unsafe(no_mangle)]
// #[cfg_attr(target_os = "macos", unsafe(link_section = ".cnt_bkp_buffer,cnt.BUFFER"))]
// #[cfg_attr(not(target_os = "macos"), link_section = ".cnt_bkp_buffer.cnt.BUFFER")]
static mut _CNT_BKP_BUFFER: [u32; BKP_BUF_SIZE] = [0; BKP_BUF_SIZE];

#[inline(always)]
pub fn counters_bkp_buffer() -> &'static [u32] {
    unsafe {
        core::slice::from_raw_parts(
            &raw const _CNT_BKP_BUFFER as *const _ as *const u32,
            BKP_BUF_SIZE,
        )
    }
}

// Counters are updated through raw pointers, without creating references to the buffers: an interrupt can preempt an
// update of one counter to update another one, and two `&mut` to the same buffer would be UB even though they touch
// different words.
//
// Counters are never shared, by design: every cnt macro invocation reserves its own index. It is the address of a
// `CNT_INDEX` static, one byte per 32-bit word of the counter, placed in a non-allocated (INFO) section starting at 0
// (see cnt.x), so the linker hands out non-repeating indices and a counter is only ever updated from one call site.
// This is what makes the non-atomic read-modify-write sound.
//
// Limitation of the current design: one call site can still run in several contexts, e.g. a function containing a
// cnt macro that is called both from thread mode and from an interrupt. If the interrupt preempts an update of the same
// counter, its increment is lost. A u64 counter is additionally written as two words, so a preemption between them
// around a carry into the high word can leave a corrupted value. Formally this is a data race, like any non-atomic
// static shared with an interrupt.

/// Add `rhs` to a u32 RAM counter, saturating at the maximum value. Used by the code generated by the cnt macros.
///
/// # Safety
///
/// `counter_idx` must be the index of a u32 counter reserved by a cnt macro invocation. Panics if it is out of bounds.
#[inline(always)]
pub unsafe fn saturating_add_u32_ram(counter_idx: usize, rhs: u32) {
    unsafe {
        let value = &raw mut _CNT_RAM_BUFFER[counter_idx];
        value.write(value.read().saturating_add(rhs));
    }
}

/// Add `rhs` to a u32 BKP counter, saturating at the maximum value. Used by the code generated by the cnt macros.
///
/// # Safety
///
/// `counter_idx` must be the index of a u32 counter reserved by a cnt macro invocation. Panics if it is out of bounds.
#[inline(always)]
pub unsafe fn saturating_add_u32_bkp(counter_idx: usize, rhs: u32) {
    unsafe {
        let value = &raw mut _CNT_BKP_BUFFER[counter_idx];
        value.write(value.read().saturating_add(rhs));
    }
}

/// Add `rhs` to a u64 RAM counter, saturating at the maximum value. Used by the code generated by the cnt macros.
///
/// # Safety
///
/// `counter_idx_lo` must be the index of a u64 counter reserved by a cnt macro invocation, so that it and
/// `counter_idx_lo + 1` are within the buffer, which is not checked.
pub unsafe fn saturating_add_u64_ram(counter_idx_lo: usize, rhs: u64) {
    unsafe {
        saturating_add_u64(
            (&raw mut _CNT_RAM_BUFFER).cast::<u32>().add(counter_idx_lo),
            rhs,
        );
    }
}

/// Add `rhs` to a u64 BKP counter, saturating at the maximum value. Used by the code generated by the cnt macros.
///
/// # Safety
///
/// `counter_idx_lo` must be the index of a u64 counter reserved by a cnt macro invocation, so that it and
/// `counter_idx_lo + 1` are within the buffer, which is not checked.
pub unsafe fn saturating_add_u64_bkp(counter_idx_lo: usize, rhs: u64) {
    unsafe {
        saturating_add_u64(
            (&raw mut _CNT_BKP_BUFFER).cast::<u32>().add(counter_idx_lo),
            rhs,
        );
    }
}

/// Add `rhs` to the u64 stored as two 32-bit words at `lo`, low word first.
///
/// The buffers are only 4-byte aligned, so a u64 counter is accessed as two aligned u32 words instead of through an
/// (unaligned) `*mut u64`. This also avoids byte-wise unaligned accesses on cores without unaligned access support.
///
/// # Safety
///
/// `lo` and `lo + 1` must be valid for reads and writes.
#[inline(always)]
unsafe fn saturating_add_u64(lo: *mut u32, rhs: u64) {
    unsafe {
        let hi = lo.add(1);
        let value = (u64::from(hi.read()) << 32 | u64::from(lo.read())).saturating_add(rhs);
        lo.write(value as u32);
        hi.write((value >> 32) as u32);
    }
}

#[cfg(test)]
mod tests {
    use super::saturating_add_u64;

    fn add(words: &mut [u32; 2], rhs: u64) {
        unsafe { saturating_add_u64(words.as_mut_ptr(), rhs) }
    }

    #[test]
    fn u64_carries_into_high_word() {
        let mut words = [u32::MAX, 0];
        add(&mut words, 1);
        assert_eq!(words, [0, 1]);
        add(&mut words, 0x1_0000_0002);
        assert_eq!(words, [2, 2]);
    }

    #[test]
    fn u64_saturates() {
        let mut words = [u32::MAX - 1, u32::MAX];
        add(&mut words, 5);
        assert_eq!(words, [u32::MAX, u32::MAX]);
    }
}
