#![no_std]

use crate::consts::{BKP_BUF_SIZE, RAM_BUF_SIZE};
pub use cnt_macro::{bkp_cnt_if, cnt_if};

mod consts;

#[used]
#[unsafe(no_mangle)]
#[cfg_attr(target_os = "macos", unsafe(link_section = ".rodata,cnt_signature"))]
#[cfg_attr(
    not(target_os = "macos"),
    unsafe(link_section = ".rodata.cnt_signature")
)]
static mut _CNT_SIGNATURE: [u8; 8] = [0; 8];

#[unsafe(no_mangle)]
static mut _CNT_RAM_BUFFER: [u32; RAM_BUF_SIZE] = [0; RAM_BUF_SIZE];

#[inline(always)]
pub fn counters_ram_buffer() -> &'static [u32] {
    unsafe {
        core::slice::from_raw_parts(
            &raw const _CNT_RAM_BUFFER as *const _ as *const u32,
            RAM_BUF_SIZE,
        )
    }
}

#[inline(always)]
fn counters_ram_buffer_mut() -> &'static mut [u32] {
    unsafe {
        core::slice::from_raw_parts_mut(
            &raw mut _CNT_RAM_BUFFER as *mut _ as *mut u32,
            RAM_BUF_SIZE,
        )
    }
}

#[unsafe(no_mangle)]
// #[cfg_attr(target_os = "macos", unsafe(link_section = ".cnt_bkp_buffer,cnt.BUFFER"))]
// #[cfg_attr(not(target_os = "macos"), link_section = ".cnt_bkp_buffer.cnt.BUFFER")]
static mut _CNT_BKP_BUFFER: [u32; BKP_BUF_SIZE] = [0; BKP_BUF_SIZE];

#[inline(always)]
pub fn counters_bkp_buffer() -> &'static [u32] {
    unsafe {
        core::slice::from_raw_parts(
            &raw const _CNT_BKP_BUFFER as *const _ as *const u32,
            BKP_BUF_SIZE,
        )
    }
}

#[inline(always)]
fn counters_bkp_buffer_mut() -> &'static mut [u32] {
    unsafe {
        core::slice::from_raw_parts_mut(
            &raw mut _CNT_BKP_BUFFER as *mut _ as *mut u32,
            BKP_BUF_SIZE,
        )
    }
}

/// Add `rhs` to a u32 RAM counter, saturating at the maximum value. Used by the code generated by the cnt macros.
///
/// # Safety
///
/// Must not be called concurrently for the same counter (e.g. from thread mode and an interrupt), as the update is
/// not atomic. Panics if `counter_idx` is out of bounds.
#[inline(always)]
pub unsafe fn saturating_add_u32_ram(counter_idx: usize, rhs: u32) {
    let buffer = counters_ram_buffer_mut();
    buffer[counter_idx] = buffer[counter_idx].saturating_add(rhs);
}

/// Add `rhs` to a u32 BKP counter, saturating at the maximum value. Used by the code generated by the cnt macros.
///
/// # Safety
///
/// Must not be called concurrently for the same counter (e.g. from thread mode and an interrupt), as the update is
/// not atomic. Panics if `counter_idx` is out of bounds.
#[inline(always)]
pub unsafe fn saturating_add_u32_bkp(counter_idx: usize, rhs: u32) {
    let buffer = counters_bkp_buffer_mut();
    buffer[counter_idx] = buffer[counter_idx].saturating_add(rhs);
}

/// Add `rhs` to a u64 RAM counter, saturating at the maximum value. Used by the code generated by the cnt macros.
///
/// # Safety
///
/// `counter_idx_lo` and `counter_idx_lo + 1` must be within the RAM counters buffer, which is not checked. Must not be
/// called concurrently for the same counter (e.g. from thread mode and an interrupt), as the update is not atomic.
pub unsafe fn saturating_add_u64_ram(counter_idx_lo: usize, rhs: u64) {
    unsafe {
        let value = counters_ram_buffer_mut().as_mut_ptr().add(counter_idx_lo) as *mut u64;
        *value = (*value).saturating_add(rhs);
    }
}

/// Add `rhs` to a u64 BKP counter, saturating at the maximum value. Used by the code generated by the cnt macros.
///
/// # Safety
///
/// `counter_idx_lo` and `counter_idx_lo + 1` must be within the BKP counters buffer, which is not checked. Must not be
/// called concurrently for the same counter (e.g. from thread mode and an interrupt), as the update is not atomic.
pub unsafe fn saturating_add_u64_bkp(counter_idx_lo: usize, rhs: u64) {
    unsafe {
        let value = counters_bkp_buffer_mut().as_mut_ptr().add(counter_idx_lo) as *mut u64;
        *value = (*value).saturating_add(rhs);
    }
}
